version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: fund_transfer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8081:8080

  backend:
    build: ./fund_transfer
    container_name: fund_transfer_container
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./fund_transfer:/app
    working_dir: /app
    command: >
        ./mvnw spring-boot:run 
        -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fund_transfer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

volumes:
  pgdata:
